"use client";

import { useSyncExternalStore } from "react";

export type Language = "en" | "my";
const STORAGE_KEY = "anonspace-language";
const CHANGE_EVENT = "anonspace-language-change";

function subscribe(callback: () => void) {
  window.addEventListener(CHANGE_EVENT, callback);
  window.addEventListener("storage", callback);
  return () => {
    window.removeEventListener(CHANGE_EVENT, callback);
    window.removeEventListener("storage", callback);
  };
}

function getSnapshot(): Language {
  try {
    return localStorage.getItem(STORAGE_KEY) === "my" ? "my" : "en";
  } catch {
    return "en";
  }
}

export function useLanguage(): Language {
  return useSyncExternalStore(subscribe, getSnapshot, () => "en");
}

export function setLanguage(language: Language) {
  localStorage.setItem(STORAGE_KEY, language);
  document.documentElement.lang = language;
  window.dispatchEvent(new Event(CHANGE_EVENT));
}

const my: Record<string, string> = {
  "Language": "ဘာသာစကား",
  "Log In": "ဝင်ရန်",
  "Sign Up": "စာရင်းသွင်းရန်",
  "Sign In": "ဝင်ရန်",
  "Signing in...": "ဝင်နေသည်...",
  "Get Started": "စတင်ရန်",
  "Speak Freely.": "လွတ်လပ်စွာ ပြောပါ။",
  "Stay Anonymous.": "အမည်ဝှက်ထားပါ။",
  "Join millions who trust AnonSpace to protect their identity while sharing what matters most.": "သင့်ကိုယ်ရေးအမှတ်အသားကို ကာကွယ်ရင်း အရေးကြီးသော အကြောင်းအရာများကို AnonSpace တွင် မျှဝေပါ။",
  "Post anonymously": "အမည်ဝှက်ဖြင့် ပို့စ်တင်ရန်",
  "No real names, no profiles tied to your identity. Just a handle and a voice.": "အမည်ရင်းမလိုပါ။ သင့်အမည်ဝှက်နှင့် အသံကိုသာ အသုံးပြုပါ။",
  "Join communities": "အသိုင်းအဝိုင်းများသို့ ဝင်ရန်",
  "Find people talking about what you care about, from dev to design to privacy.": "သင်စိတ်ဝင်စားသော အကြောင်းအရာများကို ဆွေးနွေးသူများနှင့် တွေ့ဆုံပါ။",
  "Private, encrypted chat": "လုံခြုံသော သီးသန့်စကားပြောခန်း",
  "Private Chat": "သီးသန့်စကားပြောခန်း",
  "Blocked": "ပိတ်ဆို့ထားသည်",
  "Block": "ပိတ်ဆို့ရန်",
  "Back to conversations": "စကားပြောစာရင်းသို့ ပြန်ရန်",
  "Minimize chat": "စကားပြောခန်း ချုံ့ရန်",
  "Minimize": "ချုံ့ရန်",
  "Close chat": "စကားပြောခန်း ပိတ်ရန်",
  "You've blocked this account.": "ဤအကောင့်ကို ပိတ်ဆို့ထားသည်။",
  "Selected attachment": "ရွေးထားသော ဖိုင်",
  "Attachment": "တွဲထားသော ဖိုင်",
  "Say hello to": "မင်္ဂလာပါ ဟုပြောပါ —",
  "Remove attachment": "ဖိုင် ဖယ်ရန်",
  "Attach a photo or video": "ဓာတ်ပုံ သို့မဟုတ် ဗီဒီယို တွဲရန်",
  "Send an anonymous message...": "အမည်ဝှက်စာ ပို့ပါ...",
  "Send message": "စာပို့ရန်",
  "Open private chat": "သီးသန့်စကားပြောခန်း ဖွင့်ရန်",
  "Private chat": "သီးသန့်စကားပြောခန်း",
  "You": "သင်",
  "Admins can't message other accounts": "စီမံခန့်ခွဲသူများ စာမပို့နိုင်ပါ",
  "Admins can't message other accounts.": "စီမံခန့်ခွဲသူများ အခြားအကောင့်များကို စာမပို့နိုင်ပါ။",
  "Search accounts to message...": "စာပို့ရန် အကောင့်များ ရှာပါ...",
  "Searching...": "ရှာနေသည်...",
  "No accounts match": "ကိုက်ညီသော အကောင့်မရှိပါ",
  "No conversations yet. Search for an account above, or tap someone's name on a post or comment to message them.": "စကားပြောထားခြင်း မရှိသေးပါ။ အပေါ်တွင် အကောင့်တစ်ခုကို ရှာပါ၊ သို့မဟုတ် ပို့စ်/မှတ်ချက်ပေါ်ရှိ အမည်ကို နှိပ်ပြီး စာပို့ပါ။",
  "Message anyone one-on-one without exposing who you are.": "မည်သူနှင့်မဆို အမည်မဖော်ဘဲ သီးသန့်စကားပြောပါ။",
  "End-to-end encrypted": "အစမှအဆုံး စာဝှက်ထားသည်",
  "Zero-knowledge": "အချက်အလက် မသိမ်းဆည်းမှု",
  "Welcome Back": "ပြန်လည်ကြိုဆိုပါသည်",
  "Your identity is always protected.": "သင့်ကိုယ်ရေးအမှတ်အသားကို အမြဲကာကွယ်ထားသည်။",
  "Email Address": "အီးမေးလ်လိပ်စာ",
  "Forgot password?": "စကားဝှက် မေ့နေပါသလား။",
  "Enter at least 8 characters": "အနည်းဆုံး စာလုံး ၈ လုံး ရိုက်ထည့်ပါ",
  "Don't have an account?": "အကောင့် မရှိသေးပါသလား။",
  "Register": "စာရင်းသွင်းရန်",
  "Create Your Account": "အကောင့် ဖန်တီးရန်",
  "We'll email you a 6-digit code to verify it's really you. You'll get a random anonymous name automatically — no need to pick one.": "အတည်ပြုရန် ဂဏန်း ၆ လုံးပါ ကုဒ်ကို အီးမေးလ်ဖြင့် ပို့ပါမည်။ အမည်ဝှက်ကို အလိုအလျောက် ပေးပါမည်။",
  "Sending code...": "ကုဒ်ပို့နေသည်...",
  "Send Verification Code": "အတည်ပြုကုဒ် ပို့ရန်",
  "Check Your Email": "အီးမေးလ် စစ်ဆေးပါ",
  "Enter the 6-digit code we sent to": "သို့ပို့ထားသော ဂဏန်း ၆ လုံးပါ ကုဒ်ကို ရိုက်ထည့်ပါ —",
  "Verification Code": "အတည်ပြုကုဒ်",
  "Verifying...": "အတည်ပြုနေသည်...",
  "Verify Code": "ကုဒ် အတည်ပြုရန်",
  "Resending code...": "ကုဒ် ထပ်ပို့နေသည်...",
  "Resend code in": "ကုဒ် ထပ်ပို့နိုင်ရန်",
  "Resend code": "ကုဒ် ထပ်ပို့ရန်",
  "Use a different email": "အခြား အီးမေးလ် အသုံးပြုရန်",
  "Set Your Password": "စကားဝှက် သတ်မှတ်ရန်",
  "Email verified. Choose a password to finish creating your account.": "အီးမေးလ် အတည်ပြုပြီးပါပြီ။ အကောင့်ဖန်တီးရန် စကားဝှက် သတ်မှတ်ပါ။",
  "Confirm Password": "စကားဝှက် အတည်ပြုပါ",
  "Re-enter your password": "စကားဝှက် ထပ်ရိုက်ပါ",
  "Creating account...": "အကောင့် ဖန်တီးနေသည်...",
  "Create Account": "အကောင့် ဖန်တီးရန်",
  "Already have an account?": "အကောင့်ရှိပြီးသားလား။",
  "Reset Your Password": "စကားဝှက် ပြန်သတ်မှတ်ရန်",
  "Enter the email on your account and we'll send you a 6-digit code to verify it's really you.": "သင့်အကောင့်၏ အီးမေးလ်ကို ရိုက်ထည့်ပါ။ အတည်ပြုရန် ဂဏန်း ၆ လုံးပါ ကုဒ်ကို ပို့ပါမည်။",
  "Set a New Password": "စကားဝှက်အသစ် သတ်မှတ်ရန်",
  "Email verified. Choose a new password for your account.": "အီးမေးလ် အတည်ပြုပြီးပါပြီ။ စကားဝှက်အသစ် ရွေးပါ။",
  "New Password": "စကားဝှက်အသစ်",
  "Confirm New Password": "စကားဝှက်အသစ်ကို အတည်ပြုပါ",
  "Re-enter your new password": "စကားဝှက်အသစ် ထပ်ရိုက်ပါ",
  "Reset Password": "စကားဝှက် ပြန်သတ်မှတ်ရန်",
  "Password Updated": "စကားဝှက် ပြောင်းပြီးပါပြီ",
  "Your password has been reset. Log in with your new password.": "စကားဝှက် ပြန်သတ်မှတ်ပြီးပါပြီ။ စကားဝှက်အသစ်ဖြင့် ဝင်ပါ။",
  "Go to Log In": "ဝင်ရန် သွားပါ",
  "Remembered it after all?": "စကားဝှက် ပြန်မှတ်မိပြီလား။",
  "Choose the language used in AnonSpace on this device.": "ဤစက်ပေါ်ရှိ AnonSpace တွင် အသုံးပြုမည့် ဘာသာစကားကို ရွေးပါ။",
  "English": "အင်္ဂလိပ်",
  "Burmese": "မြန်မာ",
  "Setting": "ဆက်တင်",
  "Settings": "ဆက်တင်များ",
  "Appearance and account preferences.": "ပုံစံနှင့် အကောင့်ဆိုင်ရာ ရွေးချယ်မှုများ။",
  "Appearance": "အသွင်အပြင်",
  "Toggle theme": "အသွင်အပြင် ပြောင်းရန်",
  "Choose how AnonSpace looks on this device.": "ဤစက်ပေါ်တွင် AnonSpace ၏ အသွင်အပြင်ကို ရွေးပါ။",
  "Light": "အလင်းရောင်",
  "Dark": "အမှောင်",
  "Account": "အကောင့်",
  "Your identity on AnonSpace.": "AnonSpace ပေါ်ရှိ သင့်ကိုယ်ရေးအမှတ်အသား။",
  "Anonymous name": "အမည်ဝှက်",
  "Refresh": "အမည်ပြောင်းရန်",
  "Roll a new name": "အမည်အသစ် ပြောင်းရန်",
  "Available again": "ပြန်လည်ရရှိမည့်အချိန်",
  "Roll a new anonymous name? Your past posts and comments will keep showing your old one.": "အမည်ဝှက်အသစ် ပြောင်းမည်လား။ ပို့စ်နှင့် မှတ်ချက်ဟောင်းများတွင် အမည်ဟောင်းကို ဆက်လက်ပြသပါမည်။",
  "You can refresh your name on": "အမည်ပြောင်းနိုင်မည့်ရက်",
  "every 6 months from the date you created your account.": "အကောင့်ဖွင့်သည့်ရက်မှ ၆ လတစ်ကြိမ် ပြောင်းနိုင်ပါသည်။",
  "Email": "အီးမေးလ်",
  "Password": "စကားဝှက်",
  "Change the password used to log in.": "ဝင်ရောက်ရာတွင် အသုံးပြုသော စကားဝှက်ကို ပြောင်းပါ။",
  "Current password": "လက်ရှိ စကားဝှက်",
  "New password": "စကားဝှက်အသစ်",
  "Confirm new password": "စကားဝှက်အသစ်ကို အတည်ပြုပါ",
  "At least 8 characters": "အနည်းဆုံး စာလုံး ၈ လုံး",
  "Update password": "စကားဝှက် ပြောင်းရန်",
  "Updating...": "ပြောင်းနေသည်...",
  "Password updated.": "စကားဝှက် ပြောင်းပြီးပါပြီ။",
  "Forgot your current password?": "လက်ရှိ စကားဝှက် မေ့နေပါသလား။",
  "New passwords don't match.": "စကားဝှက်အသစ်နှစ်ခု မတူညီပါ။",
  "Notifications": "အသိပေးချက်များ",
  "Mark all read": "အားလုံးကို ဖတ်ပြီးဟု မှတ်ရန်",
  "Mark as read": "ဖတ်ပြီးဟု မှတ်ရန်",
  "Choose which alerts you want to receive.": "လက်ခံလိုသော အသိပေးချက်များကို ရွေးပါ။",
  "Someone comments on my post": "ကျွန်ုပ်၏ ပို့စ်တွင် တစ်ဦးဦး မှတ်ချက်ရေးသည့်အခါ",
  "Someone reports my post, comment, or account": "ကျွန်ုပ်၏ ပို့စ်၊ မှတ်ချက် သို့မဟုတ် အကောင့်ကို တိုင်ကြားသည့်အခါ",
  "My post or comment gets banned": "ကျွန်ုပ်၏ ပို့စ် သို့မဟုတ် မှတ်ချက် ပိတ်ပင်ခံရသည့်အခါ",
  "My account gets banned": "ကျွန်ုပ်၏ အကောင့် ပိတ်ပင်ခံရသည့်အခါ",
  "A report I filed gets approved": "ကျွန်ုပ်၏ တိုင်ကြားချက် အတည်ပြုခံရသည့်အခါ",
  "A report I filed gets dismissed": "ကျွန်ုပ်၏ တိုင်ကြားချက် ပယ်ချခံရသည့်အခါ",
  "Blocked accounts": "ပိတ်ဆို့ထားသော အကောင့်များ",
  "Accounts you won't see or hear from.": "သင် မမြင်ရ၊ ဆက်သွယ်မရစေရန် ပိတ်ဆို့ထားသော အကောင့်များ။",
  "You haven't blocked anyone.": "မည်သူ့ကိုမျှ ပိတ်ဆို့ထားခြင်း မရှိပါ။",
  "Unblock": "ပိတ်ဆို့မှု ဖြုတ်ရန်",
  "Session": "လက်ရှိ အသုံးပြုမှု",
  "Sign out of AnonSpace on this device.": "ဤစက်မှ AnonSpace အကောင့်ထွက်ပါ။",
  "Log Out": "အကောင့်ထွက်ရန်",
  "Log out of AnonSpace?": "AnonSpace မှ အကောင့်ထွက်မည်လား။",
  "Loading...": "ဖွင့်နေသည်...",
  "Something went wrong.": "တစ်ခုခု မှားယွင်းသွားသည်။",
  "News": "သတင်းများ",
  "For You": "သင့်အတွက်",
  "Popular": "လူကြိုက်များသော",
  "Popular Posts": "လူကြိုက်များသော ပို့စ်များ",
  "Saved": "သိမ်းထားသော",
  "Saved Posts": "သိမ်းထားသော ပို့စ်များ",
  "Chat": "စကားပြောရန်",
  "Joined Communities": "ဝင်ထားသော အသိုင်းအဝိုင်းများ",
  "Join a community to see it here.": "ဤနေရာတွင် မြင်ရရန် အသိုင်းအဝိုင်းတစ်ခုသို့ ဝင်ပါ။",
  "Trending Communities": "ရေပန်းစားသော အသိုင်းအဝိုင်းများ",
  "My Communities": "ကျွန်ုပ်၏ အသိုင်းအဝိုင်းများ",
  "More": "နောက်ထပ်",
  "+ New Community": "+ အသိုင်းအဝိုင်းအသစ်",
  "Menu": "မီနူး",
  "Open menu": "မီနူး ဖွင့်ရန်",
  "Close menu": "မီနူး ပိတ်ရန်",
  "View your posts": "သင့်ပို့စ်များကို ကြည့်ရန်",
  "Find anything...": "ရှာဖွေပါ...",
  "Post": "ပို့စ်",
  "Post now": "ပို့စ်တင်ရန်",
  "Create a Post": "ပို့စ်ရေးရန်",
  "Share text, photos, or a video — anonymously.": "စာ၊ ဓာတ်ပုံ သို့မဟုတ် ဗီဒီယိုကို အမည်ဝှက်ဖြင့် မျှဝေပါ။",
  "Posting to": "ပို့စ်တင်မည့်နေရာ",
  "Search your communities...": "သင့်အသိုင်းအဝိုင်းများကို ရှာပါ...",
  "No matches.": "ကိုက်ညီမှု မရှိပါ။",
  "Public": "အများမြင်",
  "What's on your mind?": "ဘာတွေ စဉ်းစားနေပါသလဲ။",
  "Video": "ဗီဒီယို",
  "Remove photo": "ဓာတ်ပုံ ဖယ်ရန်",
  "Up to 10 photos, 8MB each.": "ဓာတ်ပုံ ၁၀ ပုံအထိ၊ တစ်ပုံလျှင် ၈ MB အထိ။",
  "Up to 50MB.": "၅၀ MB အထိ။",
  "Posting...": "တင်နေသည်...",
  "Anonymous": "အမည်ဝှက်",
  "Every public post, ranked by communities and creators you interact with.": "သင် အပြန်အလှန် ဆက်သွယ်လေ့ရှိသည့် အသိုင်းအဝိုင်းများနှင့် ရေးသားသူများအလိုက် စီထားသော အများမြင်ပို့စ်များ။",
  "No posts are available yet. Be the first to post!": "ပို့စ်မရှိသေးပါ။ ပထမဆုံး ပို့စ်တင်သူ ဖြစ်လိုက်ပါ။",
  "No posts yet.": "ပို့စ်မရှိသေးပါ။",
  "You haven't saved any posts yet.": "ပို့စ်တစ်ခုမျှ မသိမ်းထားသေးပါ။",
  "Try again": "ထပ်ကြိုးစားရန်",
  "Loading more...": "နောက်ထပ် ဖွင့်နေသည်...",
  "You're all caught up.": "ပို့စ်အားလုံး ကြည့်ပြီးပါပြီ။",
  "Refresh feed": "ပို့စ်စာရင်း ပြန်ဖွင့်ရန်",
  "Loading posts": "ပို့စ်များ ဖွင့်နေသည်",
  "Could not load your feed.": "ပို့စ်စာရင်းကို ဖွင့်မရပါ။",
  "Your Posts": "သင့်ပို့စ်များ",
  "You haven't posted anything yet.": "ပို့စ်တစ်ခုမျှ မတင်ရသေးပါ။",
  "Search": "ရှာဖွေရန်",
  "Search posts and communities...": "ပို့စ်နှင့် အသိုင်းအဝိုင်းများ ရှာပါ...",
  "No results for": "ရလဒ် မတွေ့ပါ",
  "That's everything.": "အားလုံး ပြသပြီးပါပြီ။",
  "Create a Community": "အသိုင်းအဝိုင်း ဖန်တီးရန်",
  "Start a space for people to gather around a shared topic — anonymously.": "အကြောင်းအရာတစ်ခုကို အမည်ဝှက်ဖြင့် ဆွေးနွေးနိုင်မည့် အသိုင်းအဝိုင်း ဖန်တီးပါ။",
  "Community name": "အသိုင်းအဝိုင်းအမည်",
  "Topic": "အကြောင်းအရာ",
  "What's this community about?": "ဤအသိုင်းအဝိုင်းသည် ဘာအကြောင်းလဲ။",
  "Visibility": "မြင်နိုင်မှု",
  "Anyone can find and join": "မည်သူမဆို ရှာတွေ့ပြီး ဝင်နိုင်သည်",
  "Private": "သီးသန့်",
  "Only visible to you": "သင်သာ မြင်နိုင်သည်",
  "Creating...": "ဖန်တီးနေသည်...",
  "Create Community": "အသိုင်းအဝိုင်း ဖန်တီးရန်",
  "Community not found.": "အသိုင်းအဝိုင်းကို မတွေ့ပါ။",
  "Joined": "ဝင်ထားပြီး",
  "Join": "ဝင်ရန်",
  "Community options": "အသိုင်းအဝိုင်း ရွေးချယ်မှုများ",
  "Edit community": "အသိုင်းအဝိုင်း ပြင်ရန်",
  "Manage members": "အဖွဲ့ဝင်များ စီမံရန်",
  "Search members...": "အဖွဲ့ဝင်များ ရှာရန်...",
  "No members.": "အဖွဲ့ဝင် မရှိပါ။",
  "No members match your search.": "ရှာဖွေမှုနှင့် ကိုက်ညီသော အဖွဲ့ဝင် မရှိပါ။",
  "Owner": "ပိုင်ရှင်",
  "Kick": "ထုတ်ပယ်ရန်",
  "Kicking...": "ထုတ်ပယ်နေသည်...",
  "All of their posts in this community and their comments on those posts will be permanently deleted.": "ဤအသိုင်းအဝိုင်းရှိ ထိုသူ၏ ပို့စ်များနှင့် မှတ်ချက်များကို အပြီးတိုင် ဖျက်ပါမည်။",
  "Edit": "ပြင်ရန်",
  "Banner": "မျက်နှာဖုံးပုံ",
  "Icon": "အိုင်ကွန်",
  "Upload": "တင်ရန်",
  "Remove": "ဖယ်ရန်",
  "About community": "အသိုင်းအဝိုင်းအကြောင်း",
  "Add rule": "စည်းမျဉ်း ထည့်ရန်",
  "No rules yet.": "စည်းမျဉ်း မရှိသေးပါ။",
  "Rule title": "စည်းမျဉ်းခေါင်းစဉ်",
  "Remove rule": "စည်းမျဉ်း ဖယ်ရန်",
  "Details (optional)": "အသေးစိတ် (မဖြစ်မနေ မဟုတ်ပါ)",
  "is a private community.": "သည် သီးသန့်အသိုင်းအဝိုင်း ဖြစ်သည်။",
  "Join to see its posts.": "ပို့စ်များ ကြည့်ရန် ဝင်ပါ။",
  "Community highlights": "အသိုင်းအဝိုင်း၏ ထိပ်တန်းပို့စ်များ",
  "Search posts in": "ပို့စ်များ ရှာရန် —",
  "No posts match": "ကိုက်ညီသော ပို့စ်မရှိပါ",
  "No posts yet in": "ပို့စ်မရှိသေးပါ —",
  "Latest to oldest": "အသစ်မှ အဟောင်းသို့",
  "Oldest to latest": "အဟောင်းမှ အသစ်သို့",
  "Most liked": "ထောက်ခံမဲ အများဆုံး",
  "Most disliked": "ကန့်ကွက်မဲ အများဆုံး",
  "Unpin post": "ပို့စ် ပင်ဖြုတ်ရန်",
  "pts": "မှတ်",
  "comments": "မှတ်ချက်များ",
  "Save": "သိမ်းရန်",
  "Saved post": "သိမ်းထားပြီး",
  "Edit post": "ပို့စ် ပြင်ရန်",
  "Post options": "ပို့စ် ရွေးချယ်မှုများ",
  "Pin to highlights": "ထိပ်တွင် ပင်ထားရန်",
  "Unpin": "ပင်ဖြုတ်ရန်",
  "Moderate post": "ပို့စ် စိစစ်ရန်",
  "Reposted": "ပြန်လည်မျှဝေထားသည်",
  "Pinned": "ပင်ထားသည်",
  "Original post is no longer available.": "မူရင်းပို့စ်ကို မတွေ့နိုင်တော့ပါ။",
  "Repost": "ပြန်တင်ရန်",
  "Repost to": "ပြန်တင်မည့်နေရာ",
  "Reposting...": "ပြန်တင်နေသည်...",
  "Add a caption (optional)...": "စာတန်း ထည့်ပါ (မဖြစ်မနေ မဟုတ်ပါ)...",
  "(no caption)": "(စာတန်းမရှိ)",
  "This post is from a private community, so it can only be reposted within it.": "ဤပို့စ်သည် သီးသန့်အသိုင်းအဝိုင်းမှ ဖြစ်သောကြောင့် ထိုအသိုင်းအဝိုင်းတွင်သာ ပြန်တင်နိုင်ပါသည်။",
  "Close": "ပိတ်ရန်",
  "Report": "တိုင်ကြားရန်",
  "Reported": "တိုင်ကြားပြီး",
  "Report this": "တိုင်ကြားရန် —",
  "post": "ပို့စ်",
  "comment": "မှတ်ချက်",
  "user": "အသုံးပြုသူ",
  "community": "အသိုင်းအဝိုင်း",
  "Spam or scam": "အနှောင့်အယှက်စာ သို့မဟုတ် လိမ်လည်မှု",
  "Harassment or hate speech": "နှောင့်ယှက်မှု သို့မဟုတ် အမုန်းစကား",
  "Misinformation": "သတင်းမှား",
  "Illegal content": "တရားမဝင် အကြောင်းအရာ",
  "Off-topic": "အကြောင်းအရာနှင့် မသက်ဆိုင်ခြင်း",
  "Other": "အခြား",
  "Describe the reason for this report...": "တိုင်ကြားရသည့် အကြောင်းရင်းကို ဖော်ပြပါ...",
  "Required when reporting for another reason.": "အခြားအကြောင်းရင်းကို ရွေးပါက ဖြည့်ရန် လိုအပ်သည်။",
  "Reports go to human moderators for a legality review only — this does not remove the content by itself. Ordinary downvotes still handle everything else.": "တိုင်ကြားချက်များကို စီမံခန့်ခွဲသူများက စစ်ဆေးမည်။ တိုင်ကြားရုံဖြင့် အကြောင်းအရာကို ချက်ချင်း ဖယ်ရှားမည် မဟုတ်ပါ။",
  "Submitting...": "တင်သွင်းနေသည်...",
  "Submit report": "တိုင်ကြားချက် တင်ရန်",
  "This community hasn't added an about description yet.": "ဤအသိုင်းအဝိုင်းတွင် ဖော်ပြချက် မထည့်ရသေးပါ။",
  "Created": "ဖန်တီးသည့်ရက်",
  "Message Mods": "စီမံသူများထံ စာပို့ရန်",
  "Rules": "စည်းမျဉ်းများ",
  "Reposted!": "ပြန်တင်ပြီးပါပြီ။",
  "Delete post": "ပို့စ် ဖျက်ရန်",
  "Delete this post? This can't be undone.": "ဤပို့စ်ကို ဖျက်မည်လား။ ပြန်လည်ရယူ၍ မရပါ။",
  "Post saved": "ပို့စ် သိမ်းပြီးပါပြီ။",
  "Post removed from saved posts": "သိမ်းထားသော ပို့စ်များမှ ဖယ်ရှားပြီးပါပြီ။",
  "Upvote": "ထောက်ခံမဲ",
  "Downvote": "ကန့်ကွက်မဲ",
  "Description": "ဖော်ပြချက်",
  "Photos": "ဓာတ်ပုံများ",
  "Add photos": "ဓာတ်ပုံ ထည့်ရန်",
  "Post photo": "ပို့စ်ဓာတ်ပုံ",
  "New photo": "ဓာတ်ပုံအသစ်",
  "Remove existing photo": "ရှိပြီးသား ဓာတ်ပုံ ဖယ်ရန်",
  "Remove new photo": "ဓာတ်ပုံအသစ် ဖယ်ရန်",
  "Close editor": "ပြင်ဆင်မှု ပိတ်ရန်",
  "Cancel": "မလုပ်တော့ပါ",
  "Saving...": "သိမ်းနေသည်...",
  "Save changes": "ပြောင်းလဲမှုများ သိမ်းရန်",
  "A post can have at most 10 photos.": "ပို့စ်တစ်ခုတွင် ဓာတ်ပုံ ၁၀ ပုံအထိ ထည့်နိုင်ပါသည်။",
  "Photos must be JPG, PNG, GIF, or WebP and no larger than 8 MB each.": "ဓာတ်ပုံများသည် JPG၊ PNG၊ GIF သို့မဟုတ် WebP ဖြစ်ပြီး တစ်ပုံလျှင် ၈ MB ထက် မကြီးရပါ။",
  "Write a description before saving.": "မသိမ်းမီ ဖော်ပြချက် ရေးပါ။",
  "Could not update the post.": "ပို့စ်ကို ပြင်ဆင်မရပါ။",
  "Video posts support description edits only.": "ဗီဒီယိုပို့စ်တွင် ဖော်ပြချက်ကိုသာ ပြင်နိုင်ပါသည်။",
  "Share": "မျှဝေရန်",
  "Copied!": "ကူးယူပြီးပါပြီ။",
  "Copy link": "လင့်ခ် ကူးယူရန်",
  "Send to...": "ပို့ရန်...",
  "Comment": "မှတ်ချက်",
  "Comments": "မှတ်ချက်များ",
  "Commenting...": "မှတ်ချက်တင်နေသည်...",
  "Add a comment...": "မှတ်ချက်ရေးပါ...",
  "No comments yet.": "မှတ်ချက်မရှိသေးပါ။",
  "Admins can't comment.": "စီမံခန့်ခွဲသူများ မှတ်ချက်မရေးနိုင်ပါ။",
  "Back": "ပြန်သွားရန်",
  "Post not found.": "ပို့စ်ကို မတွေ့ပါ။",
  "Me": "ကျွန်ုပ်",
  "Banned comment": "ပိတ်ပင်ထားသော မှတ်ချက်",
  "Reply": "ပြန်စာရေးရန်",
  "Replying...": "ပြန်စာတင်နေသည်...",
  "Reply to": "ပြန်စာရေးရန်",
  "reply": "ပြန်စာ",
  "replies": "ပြန်စာများ",
  "Hide": "ဝှက်ရန်",
  "Delete comment": "မှတ်ချက် ဖျက်ရန်",
  "Delete this comment? This can't be undone.": "ဤမှတ်ချက်ကို ဖျက်မည်လား။ ပြန်လည်ရယူ၍ မရပါ။",
  "Comment options": "မှတ်ချက် ရွေးချယ်မှုများ",
  "Manage your admin account": "စီမံခန့်ခွဲသူ အကောင့်ကို စီမံပါ",
  "Automatic bans": "အလိုအလျောက် ပိတ်ပင်မှုများ",
  "Superadmin only. Set the downvote percentage and minimum total votes required to automatically ban a post or comment.": "အမြင့်ဆုံးစီမံခန့်ခွဲသူအတွက်သာ။ ပို့စ် သို့မဟုတ် မှတ်ချက်ကို အလိုအလျောက် ပိတ်ပင်ရန် လိုအပ်သည့် ကန့်ကွက်မဲ ရာခိုင်နှုန်းနှင့် အနည်းဆုံး စုစုပေါင်းမဲကို သတ်မှတ်ပါ။",
  "Loading settings...": "ဆက်တင်များ ဖွင့်နေသည်...",
  "Current rule: at least": "လက်ရှိစည်းမျဉ်း — အနည်းဆုံး",
  "downvotes after": "ကန့်ကွက်မဲ၊ စုစုပေါင်းမဲ",
  "total votes.": "ရရှိပြီးနောက်။",
  "Downvote threshold (%)": "ကန့်ကွက်မဲ သတ်မှတ်ချက် (%)",
  "Minimum total votes": "အနည်းဆုံး စုစုပေါင်းမဲ",
  "Total votes means upvotes plus downvotes. Changes apply on the next vote check; existing bans stay in place.": "စုစုပေါင်းမဲဆိုသည်မှာ ထောက်ခံမဲနှင့် ကန့်ကွက်မဲ ပေါင်းခြင်းဖြစ်သည်။ ပြောင်းလဲမှုများသည် နောက်မဲစစ်ဆေးချိန်မှ စတင်သက်ရောက်သည်။",
  "Auto-ban settings saved.": "အလိုအလျောက် ပိတ်ပင်မှု ဆက်တင်များ သိမ်းပြီးပါပြီ။",
  "Save auto-ban settings": "အလိုအလျောက် ပိတ်ပင်မှု ဆက်တင်များ သိမ်းရန်",
  "Manage your account and platform moderation rules": "သင့်အကောင့်နှင့် စနစ်စည်းမျဉ်းများကို စီမံပါ",
  "Change the password used to log in to this admin account.": "ဤစီမံခန့်ခွဲသူ အကောင့်၏ စကားဝှက်ကို ပြောင်းပါ။",
  "Overview": "အကျဉ်းချုပ်",
  "Admin Dashboard": "စီမံခန့်ခွဲသူ ဒက်ရှ်ဘုတ်",
  "(no creator on record)": "(ဖန်တီးသူ မှတ်တမ်းမရှိ)",
  "Post Activity": "ပို့စ် လှုပ်ရှားမှု",
  "Banned rate": "ပိတ်ပင်မှုနှုန်း",
  "Last 24 hours": "ပြီးခဲ့သည့် ၂၄ နာရီ",
  "All time": "အချိန်အားလုံး",
  "actions": "လုပ်ဆောင်ချက်များ",
  "hasn't taken any actions yet.": "လုပ်ဆောင်ချက် မရှိသေးပါ။",
  "Admin not found.": "စီမံခန့်ခွဲသူကို မတွေ့ပါ။",
  "Revoke admin access for this account? They'll go back to a regular user.": "ဤအကောင့်၏ စီမံသူခွင့်ပြုချက်ကို ရုပ်သိမ်းမည်လား။ ပုံမှန်အသုံးပြုသူ ဖြစ်သွားပါမည်။",
  "Superadmin-only — admin accounts can only be registered here, never through signup.": "အမြင့်ဆုံးစီမံခန့်ခွဲသူအတွက်သာ။ စီမံသူအကောင့်များကို ဤနေရာတွင်သာ ဖန်တီးနိုင်ပါသည်။",
  "Register admin": "စီမံသူ စာရင်းသွင်းရန်",
  "Search admins by name or email...": "စီမံသူအမည် သို့မဟုတ် အီးမေးလ်ဖြင့် ရှာရန်...",
  "admin accounts": "စီမံသူအကောင့်များ",
  "Name": "အမည်",
  "Role": "အခန်းကဏ္ဍ",
  "No admins match": "ကိုက်ညီသော စီမံသူ မရှိပါ",
  "Revoke": "ခွင့်ပြုချက် ရုပ်သိမ်းရန်",
  "Recent activity": "လတ်တလော လုပ်ဆောင်ချက်များ",
  "Every admin account granted or revoked, most recent first.": "စီမံသူခွင့်ပြုချက် ပေးခြင်း၊ ရုပ်သိမ်းခြင်းများကို အသစ်ဆုံးမှ ပြထားသည်။",
  "By": "လုပ်ဆောင်သူ",
  "No activity yet.": "လုပ်ဆောင်ချက် မရှိသေးပါ။",
  "Granted": "ခွင့်ပြုထားသည်",
  "Revoked": "ရုပ်သိမ်းထားသည်",
  "Back to Admins": "စီမံသူစာရင်းသို့ ပြန်ရန်",
  "Register Admin": "စီမံသူ စာရင်းသွင်းရန်",
  "We'll email a 6-digit code to verify the address before the account is created.": "အကောင့်မဖန်တီးမီ အီးမေးလ်ကို အတည်ပြုရန် ဂဏန်း ၆ လုံးပါ ကုဒ် ပို့ပါမည်။",
  "Full Name": "အမည်အပြည့်အစုံ",
  "Check Their Email": "၎င်းတို့၏ အီးမေးလ် စစ်ဆေးပါ",
  "Enter the 6-digit code sent to": "သို့ပို့ထားသော ဂဏန်း ၆ လုံးပါ ကုဒ်ကို ရိုက်ထည့်ပါ —",
  "Set a Password": "စကားဝှက် သတ်မှတ်ရန်",
  "Email verified. Choose a password for": "အီးမေးလ် အတည်ပြုပြီးပါပြီ။ စကားဝှက် ရွေးပါ —",
  "admin account.": "စီမံသူအကောင့်အတွက်။",
  "Re-enter the password": "စကားဝှက် ထပ်ရိုက်ပါ",
  "Create Admin Account": "စီမံသူအကောင့် ဖန်တီးရန်",
  "Server & content oversight — no identity data ever surfaces here": "ဆာဗာနှင့် အကြောင်းအရာကို စီမံကြည့်ရှုရန် — ကိုယ်ရေးအချက်အလက် မပြသပါ။",
  "Admin Actions": "စီမံသူ လုပ်ဆောင်ချက်များ",
  "All Actions": "လုပ်ဆောင်ချက်အားလုံး",
  "Bans": "ပိတ်ပင်မှုများ",
  "Dismissals": "ပယ်ချမှုများ",
  "Admin": "စီမံခန့်ခွဲသူ",
  "Action": "လုပ်ဆောင်ချက်",
  "Content": "အကြောင်းအရာ",
  "Reason": "အကြောင်းရင်း",
  "When": "အချိန်",
  "Banned": "ပိတ်ပင်ထားသည်",
  "Dismissed": "ပယ်ချထားသည်",
  "No admin activity yet.": "စီမံသူ လုပ်ဆောင်ချက် မရှိသေးပါ။",
  "Look up any account to review its post history — admin-only, not available to regular users.": "မည်သည့်အကောင့်မဆို ပို့စ်မှတ်တမ်းကို ရှာကြည့်နိုင်သည်။ စီမံသူများအတွက်သာ ဖြစ်သည်။",
  "Search accounts by handle...": "အမည်ဝှက်ဖြင့် အကောင့် ရှာရန်...",
  "Look up any community to review its posts and activity — includes private communities, unlike the regular Communities page.": "မည်သည့်အသိုင်းအဝိုင်းမဆို ၎င်း၏ ပို့စ်များနှင့် လှုပ်ရှားမှုကို ရှာကြည့်နိုင်သည်။ သီးသန့်အသိုင်းအဝိုင်းများလည်း ပါဝင်သည်။",
  "Search communities by name or slug...": "အသိုင်းအဝိုင်းအမည်ဖြင့် ရှာရန်...",
  "No communities match": "ကိုက်ညီသော အသိုင်းအဝိုင်း မရှိပါ",
  "Account not found.": "အကောင့်ကို မတွေ့ပါ။",
  "hasn't posted anything.": "ပို့စ် မတင်ရသေးပါ။",
  "Every visible post on AnonSpace, latest or most upvoted - search or ban directly, no report needed.": "AnonSpace ပေါ်ရှိ အများမြင်ပို့စ်အားလုံးကို ရှာဖွေ၊ ကြည့်ရှု၊ တိုက်ရိုက် ပိတ်ပင်နိုင်သည်။",
  "Search posts...": "ပို့စ်များ ရှာရန်...",
  "Latest": "အသစ်ဆုံး",
  "Every ban an admin approved and every report an admin dismissed, most recent first. Automatic downvote-ratio bans aren't shown here — see the Ban Log for those.": "စီမံသူ အတည်ပြုသည့် ပိတ်ပင်မှုနှင့် ပယ်ချသည့် တိုင်ကြားချက်များကို အသစ်ဆုံးမှ စီထားသည်။ အလိုအလျောက် ပိတ်ပင်မှုများကို ပိတ်ပင်မှုမှတ်တမ်းတွင် ကြည့်ပါ။",
  "Registered accounts": "မှတ်ပုံတင်ထားသော အကောင့်များ",
  "New signups": "စာရင်းသွင်းသူအသစ်များ",
  "New posts & comments": "ပို့စ်နှင့် မှတ်ချက်အသစ်များ",
  "Auto-bans": "အလိုအလျောက် ပိတ်ပင်မှုများ",
  "Pending reports": "စောင့်ဆိုင်းနေသော တိုင်ကြားချက်များ",
  "Active communities": "အသုံးပြုနေသော အသိုင်းအဝိုင်းများ",
  "Content near": "သတ်မှတ်ချက်အနီးရှိ အကြောင်းအရာ",
  "line": "အဆင့်",
  "minimum": "အနည်းဆုံး",
  "votes": "မဲ",
  "users only": "အသုံးပြုသူများသာ",
  "awaiting review": "စစ်ဆေးရန် စောင့်ဆိုင်းနေသည်",
  "on the platform": "စနစ်ပေါ်တွင်",
  "Today": "ယနေ့",
  "Last 7 days": "ပြီးခဲ့သည့် ၇ ရက်",
  "Last 30 days": "ပြီးခဲ့သည့် ၃၀ ရက်",
  "since midnight UTC": "UTC သန်းခေါင်မှစ၍",
  "in the last 7 days": "ပြီးခဲ့သည့် ၇ ရက်အတွင်း",
  "in the last 30 days": "ပြီးခဲ့သည့် ၃၀ ရက်အတွင်း",
  "Posts": "ပို့စ်များ",
  "Users": "အသုံးပြုသူများ",
  "Communities": "အသိုင်းအဝိုင်းများ",
  "Ban Log": "ပိတ်ပင်မှု မှတ်တမ်း",
  "Ban": "ပိတ်ပင်ရန်",
  "Ban this": "ပိတ်ပင်ရန် —",
  "Banning...": "ပိတ်ပင်နေသည်...",
  "account": "အကောင့်",
  "Describe the reason for this ban...": "ပိတ်ပင်ရသည့် အကြောင်းရင်းကို ဖော်ပြပါ...",
  "Required when banning for another reason.": "အခြားအကြောင်းရင်းကို ရွေးပါက ဖြည့်ရန် လိုအပ်သည်။",
  "This bans the": "ဤလုပ်ဆောင်ချက်သည်",
  "immediately and can't be undone from the admin panel.": "ကို ချက်ချင်း ပိတ်ပင်ပြီး စီမံသူစာမျက်နှာမှ ပြန်ဖွင့်၍ မရပါ။",
  "They'll be logged out and can't log back in.": "ထိုသူသည် အကောင့်မှ ထွက်သွားပြီး ပြန်ဝင်၍ မရပါ။",
  "Content flagged by users for admin attention, separate from vote-based bans": "အသုံးပြုသူများ တိုင်ကြားထားသော အကြောင်းအရာများ။ မဲပေးမှုကြောင့် အလိုအလျောက် ပိတ်ပင်မှုနှင့် သီးခြားဖြစ်သည်။",
  "Pick a report type to review": "စစ်ဆေးမည့် တိုင်ကြားချက်အမျိုးအစားကို ရွေးပါ",
  "Choose Posts, Accounts, Communities, or Comments from the Reports menu in the sidebar — each type shows on its own, never mixed together.": "ဘေးမီနူးမှ ပို့စ်၊ အကောင့်၊ အသိုင်းအဝိုင်း သို့မဟုတ် မှတ်ချက် တိုင်ကြားချက်များကို ရွေးပါ။",
  "open": "ဖွင့်ထားသော",
  "posts": "ပို့စ်များ",
  "communities": "အသိုင်းအဝိုင်းများ",
  "accounts": "အကောင့်များ",
  "Content & reason": "အကြောင်းအရာနှင့် အကြောင်းရင်း",
  "Reported by": "တိုင်ကြားသူ",
  "Actions": "လုပ်ဆောင်ချက်များ",
  "Loading reports...": "တိုင်ကြားချက်များ ဖွင့်နေသည်...",
  "No open": "ဖွင့်ထားသော တိုင်ကြားချက်မရှိ —",
  "to review.": "စစ်ဆေးရန်။",
  "Approve report - action the content": "တိုင်ကြားချက် အတည်ပြုပြီး အရေးယူရန်",
  "Dismiss report - no action": "တိုင်ကြားချက် ပယ်ချရန်",
  "Approve": "အတည်ပြုရန်",
  "Dismiss": "ပယ်ချရန်",
  "Approving a report bans the content or account and notifies those affected. Dismissing notifies the reporter that no violation was found.": "တိုင်ကြားချက်ကို အတည်ပြုပါက သက်ဆိုင်ရာ အကြောင်းအရာ သို့မဟုတ် အကောင့်ကို ပိတ်ပင်ပြီး အသိပေးပါမည်။ ပယ်ချပါက တိုင်ကြားသူကို အသိပေးပါမည်။",
  "Ban this account? They'll be logged out immediately and can't log back in.": "ဤအကောင့်ကို ပိတ်ပင်မည်လား။ ချက်ချင်း အကောင့်ထွက်သွားပြီး ပြန်ဝင်၍ မရပါ။",
  "Ban this community? It'll be hidden from listings/search and no one can post or join.": "ဤအသိုင်းအဝိုင်းကို ပိတ်ပင်မည်လား။ ရှာဖွေမှုမှ ဝှက်ထားပြီး ပို့စ်တင်ခြင်း သို့မဟုတ် ဝင်ခြင်း မပြုနိုင်တော့ပါ။",
  "All Categories": "အမျိုးအစားအားလုံး",
  "Post Only": "ပို့စ်သာ",
  "Comment Only": "မှတ်ချက်သာ",
  "Account Only": "အကောင့်သာ",
  "Community Only": "အသိုင်းအဝိုင်းသာ",
  "User": "အသုံးပြုသူ",
  "Community": "အသိုင်းအဝိုင်း",
  "About": "အကြောင်းအရာ",
  "Type": "အမျိုးအစား",
  "Ratio": "အချိုး",
  "Banned by": "ပိတ်ပင်သူ",
  "No bans yet.": "ပိတ်ပင်မှု မရှိသေးပါ။",
  "Automatic": "အလိုအလျောက်",
  "of": "ခု / စုစုပေါင်း",
  "Every post, comment, account, and community that's been banned — automatically by the downvote system, or by an admin acting directly or confirming a report.": "ကန့်ကွက်မဲစနစ် သို့မဟုတ် စီမံခန့်ခွဲသူက ပိတ်ပင်ထားသည့် ပို့စ်၊ မှတ်ချက်၊ အကောင့်နှင့် အသိုင်းအဝိုင်း မှတ်တမ်း။",
  "Current automatic rule: at least": "လက်ရှိ အလိုအလျောက် စည်းမျဉ်း — အနည်းဆုံး",
  "downvotes with a minimum of": "ကန့်ကွက်မဲနှင့် အနည်းဆုံး",
  "total votes, checked when a vote is cast, changed, or removed.": "စုစုပေါင်းမဲ လိုအပ်သည်။ မဲပေး၊ ပြောင်း၊ ဖျက်ချိန်တိုင်း စစ်ဆေးသည်။",
  "Loading the current automatic ban rule.": "လက်ရှိ အလိုအလျောက် ပိတ်ပင်မှုစည်းမျဉ်းကို ဖွင့်နေသည်။",
  "Earlier bans may have used different settings. Admin-confirmed bans record which admin approved them.": "ယခင်ပိတ်ပင်မှုများတွင် စည်းမျဉ်းကွဲပြားနိုင်သည်။ စီမံသူ အတည်ပြုသော ပိတ်ပင်မှုများတွင် စီမံသူအမည်ကို မှတ်တမ်းတင်ထားသည်။",
  "Reports": "တိုင်ကြားချက်များ",
  "Accounts": "အကောင့်များ",
  "Admins": "စီမံခန့်ခွဲသူများ",
  "Admin navigation": "စီမံခန့်ခွဲသူ လမ်းညွှန်မီနူး",
  "Open admin navigation": "စီမံခန့်ခွဲသူ မီနူးဖွင့်ရန်",
  "Log out": "အကောင့်ထွက်ရန်",
};

export function translate(language: Language, english: string): string {
  return language === "my" ? my[english] ?? english : english;
}

/** Notification messages are stored by the API in English; translate known templates
 * while leaving handles, community names, and user-entered reasons untouched. */
export function translateNotification(language: Language, message: string): string {
  if (language !== "my") return message;
  let match = /^(.+) commented on your post\.$/.exec(message);
  if (match) return `${match[1]} က သင့်ပို့စ်တွင် မှတ်ချက်ရေးထားသည်။`;
  match = /^Your (post|comment) in c\/(.+) was removed after receiving too many downvotes\.$/.exec(message);
  if (match) return `ကန့်ကွက်မဲများလွန်းသောကြောင့် c/${match[2]} ရှိ သင့်${translate(language, match[1])}ကို ဖယ်ရှားလိုက်သည်။`;
  match = /^Your (post|comment) in c\/(.+) was removed following a report review\.$/.exec(message);
  if (match) return `တိုင်ကြားချက်ကို စစ်ဆေးပြီးနောက် c/${match[2]} ရှိ သင့်${translate(language, match[1])}ကို ဖယ်ရှားလိုက်သည်။`;
  match = /^Your (post|comment) in c\/(.+) was removed by an admin\.$/.exec(message);
  if (match) return `စီမံခန့်ခွဲသူက c/${match[2]} ရှိ သင့်${translate(language, match[1])}ကို ဖယ်ရှားလိုက်သည်။`;
  match = /^Someone reported your account for "(.+)"\.$/.exec(message);
  if (match) return `သင့်အကောင့်ကို "${translate(language, match[1])}" အကြောင်းဖြင့် တိုင်ကြားထားသည်။`;
  match = /^Your (post|comment|community) was reported for "(.+)"\.$/.exec(message);
  if (match) return `သင့်${translate(language, match[1])}ကို "${translate(language, match[2])}" အကြောင်းဖြင့် တိုင်ကြားထားသည်။`;
  match = /^Your report was reviewed and confirmed - the (post|comment|user|community) was actioned\.$/.exec(message);
  if (match) return `သင့်တိုင်ကြားချက်ကို အတည်ပြုပြီး ${translate(language, match[1])}အပေါ် အရေးယူထားသည်။`;
  if (message === "Your report was reviewed - no policy violation was found.") return "သင့်တိုင်ကြားချက်ကို စစ်ဆေးပြီး စည်းမျဉ်းချိုးဖောက်မှု မတွေ့ရှိပါ။";
  return translate(language, message);
}

export function useTranslate() {
  const language = useLanguage();
  return (english: string) => translate(language, english);
}
